SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS;
SELECT * FROM DEPARTMENTS; -- !!!!!!!!!!! 실무에서 사용 금지 !!!!!!!!!!!!! 성능에 영향 있음

SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, DEPARTMENTS.LOCATION_ID FROM DEPARTMENTS;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, D.LOCATION_ID FROM DEPARTMENTS D;

-- 부서 테이블의 모든 칼럼 조회. 조회 칼럼명 지정: '부서번호', '부서명', '위치'
SELECT DEPARTMENT_ID AS 부서번호,
       DEPARTMENT_NAME AS 부서명,
       LOCATION_ID AS 위치
   FROM DEPARTMENTS;

SELECT DISTINCT LOCATION_ID
   FROM DEPARTMENTS;

SELECT LOCATION_ID
   FROM DEPARTMENTS
  GROUP BY LOCATION_ID;
