DROP TABLE CUSTOMER_T;
DROP TABLE BANK_T;

CREATE TABLE BANK_T (
    BANK_CODE	    VARCHAR2(20 BYTE)	NOT NULL,
    BANK_NAME	    VARCHAR2(30 BYTE),
    CONSTRAINT	    PK_BANK		PRIMARY KEY(BANK_CODE)
    );

CREATE TABLE CUSTOMER_T (
    CUST_NO  		NUMBER			NOT NULL,
    CUST_NAME		VARCHAR2(30 BYTE)   	NOT NULL,
    CUST_PHONE		VARCHAR2(30 BYTE)   	UNIQUE,
    CUST_AGE		NUMBER(3)   	    	CHECK(CUST_AGE >= 0 AND CUST_AGE <= 120),
    					    	-- CHECK(CUST_AGE BETWEEN 0 AND 120),
    BANK_CODE		VARCHAR2(20 BYTE),
    CONSTRAINT		PK_CUSTOMER 	    	PRIMARY KEY(CUST_NO),
    CONSTRAINT		FK_CUSTOMER_BANK	FOREIGN KEY(BANK_CODE) REFERENCES BANK_T(BANK_CODE)
    );

-- CONSTRAINT
--SELECT * FROM USER_CONSTRAINTS;

-- 1. BANK_T에 연락처(BANK_TEL) 칼럼 추가
ALTER TABLE BANK_T ADD BANK_TEL VARCHAR2(15 BYTE);

-- 2. BANK_T의 은행명(BANK_NAME) 칼럼을 VARCHAR2(15 BYTE)로 바꾼 후 필수 제약조건을 지정
ALTER TABLE BANK_T MODIFY BANK_NAME VARCHAR2(15 BYTE) NOT NULL;

-- 3. CUSTOMER_T의 나이(CUST_AGE) 칼럼을 삭제
ALTER TABLE CUSTOMER_T DROP COLUMN CUST_AGE;

-- 4. CUSTOMER_T의 연락처(CUST_PHONE) 칼럼명 CUST_TEL로 변경
ALTER TABLE CUSTOMER_T RENAME COLUMN CUST_PHONE TO CUST_TEL;

-- 5. CUSTOMER_T에 등급(GRADE) 칼럼 추가. 값을 'VIP', 'GOLD', 'SILVEER', 'BRONZE' 로 제한
ALTER TABLE CUSTOMER_T ADD GRADE VARCHAR2(6 BYTE) CHECK(GRADE = 'VIP' OR GRADE = 'GOLD' OR GRADE = 'SILVEER' OR GRADE = 'BRONZE');
      	    	       	   	 	    	  -- CHECK(GRADE IN('VIP', 'GOLD', 'SILER', 'BRONZE'));

-- 6. CUSTOMER_T에 고객명(CUST_NAME) 칼럼의 필수제약조건 해제
ALTER TABLE CUSTOMER_T MODIFY CUST_NAME VARCHAR2(30 BYTE) NULL;

-- 7. CUSTOMER_T의 테이블명을 CUST_T로 수정
ALTER TABLE CUSTOMER_T RENAME TO CUST_T;

/*
	1. PK
	   1) 추가	: ALTER TABLE table_name ADD CONSTRAINT constraint_name PRIMARY KEY(column_name)
	   2) 삭제
	      (1) ALTER TABLE table_name DROP CONTRAINT constraint_name
	      (2) ALTER TABLE table_name DROP PRIMARY KEY
	2. FK
	   1) 추가	: ALTER TABLE child_table_name ADD CONSTRAINT constraint_name FOREIGN KEY(column_name) REFERENCES parent_table_name(column_name) [options]
	   2) 삭제	: ALTER TABLE table_name DROP CONSTRAINT constraint_name
	   3) 비활성화	: ALTER TABLE table_name DISABLE CONTRAINT constraint_name
	   4) 활성화	: ALTER TABLE table_name ENABLE CONSTRAINT constraint_name
*/

-- FK_CUSTOMER_BANK 제약조건 비활성화
ALTER TABLE CUST_T DISABLE CONSTRAINT FK_CUSTOMER_BANK;

-- insert invalid data
INSERT INTO CUST_T VALUES (1, "undefined", "000-0000-0000", "99", "12849");

-- FK_CUSTOMER_BANK 제약조건 활성화
ALTER TABLE CUST_T ENSABLE CONSTRAINT FK_CUSTOMER_BANK;
-- yields error: delete invalid data or make parent table satisfy constraints
